#!/bin/bash
# ═══════════════════════════════════════════════════════════
# NEXUS v6.0 — One-Line Docker Install
# curl -fsSL https://raw.githubusercontent.com/***REMOVED***/nexus-toti/main/install.sh | bash
# ═══════════════════════════════════════════════════════════
set -e

# ── Colors ────────────────────────────────────────────────
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
CYAN='\033[0;36m'
BOLD='\033[1m'
NC='\033[0m'

echo ""
echo -e "${CYAN}═══════════════════════════════════════════════════════${NC}"
echo -e "${BOLD}  NEXUS v6.0 — Autonomous Multi-Agent Framework${NC}"
echo -e "${CYAN}  One-Line Docker Installation${NC}"
echo -e "${CYAN}═══════════════════════════════════════════════════════${NC}"
echo ""

# ── Pre-flight checks ────────────────────────────────────
check_command() {
    if ! command -v "$1" &>/dev/null; then
        echo -e "${RED}✗ $1 not found. Please install $1 first.${NC}"
        echo -e "  Install: $2"
        exit 1
    fi
    echo -e "${GREEN}✓${NC} $1 found: $(command -v "$1")"
}

echo -e "${BOLD}Pre-flight checks...${NC}"
check_command "docker"    "https://docs.docker.com/get-docker/"
check_command "git"        "https://git-scm.com/downloads"

# Check Docker Compose (v2 = docker compose, v1 = docker-compose)
if docker compose version &>/dev/null 2>&1; then
    COMPOSE_CMD="docker compose"
    echo -e "${GREEN}✓${NC} Docker Compose v2 found"
elif command -v docker-compose &>/dev/null; then
    COMPOSE_CMD="docker-compose"
    echo -e "${GREEN}✓${NC} Docker Compose v1 found"
else
    echo -e "${RED}✗ Docker Compose not found.${NC}"
    echo -e "  Install: https://docs.docker.com/compose/install/"
    exit 1
fi

# ── Configuration ────────────────────────────────────────
INSTALL_DIR="${NEXUS_HOME:-$HOME/nexus-toti}"
TELEGRAM_TOKEN="${NEXUS_TG_TOKEN:-}"
OLLAMA_HOST="${NEXUS_OLLAMA_HOST:-http://host.docker.internal:11434}"
MODEL_FAST="${NEXUS_MODEL_FAST:-glm-5.1:cloud}"
MODEL_STANDARD="${NEXUS_MODEL_STANDARD:-kimi-k2.6:cloud}"
MODEL_THINK="${NEXUS_MODEL_THINK:-kimi-k2.6:cloud}"
BUILD_TELEGRAM="${NEXUS_BUILD_TELEGRAM:-0}"

echo ""
echo -e "${BOLD}Configuration:${NC}"
echo -e "  Install dir:   ${CYAN}${INSTALL_DIR}${NC}"
echo -e "  Ollama host:   ${CYAN}${OLLAMA_HOST}${NC}"
echo -e "  Model fast:    ${CYAN}${MODEL_FAST}${NC}"
echo -e "  Model standard:${CYAN}${MODEL_STANDARD}${NC}"
echo -e "  Model think:   ${CYAN}${MODEL_THINK}${NC}"
echo -e "  Telegram:      ${CYAN}${BUILD_TELEGRAM}${NC}"

# ── Clone ─────────────────────────────────────────────────
echo ""
echo -e "${BOLD}${BLUE}⬇ Cloning NEXUS v6.0...${NC}"
if [ -d "$INSTALL_DIR" ]; then
    echo -e "${YELLOW}⊘ Directory exists, pulling latest...${NC}"
    cd "$INSTALL_DIR"
    git pull --ff-only 2>/dev/null || {
        echo -e "${YELLOW}⊘ Cannot pull (diverged?). Using existing checkout.${NC}"
    }
else
    git clone https://github.com/***REMOVED***/nexus-toti.git "$INSTALL_DIR"
fi
cd "$INSTALL_DIR"
echo -e "${GREEN}✓ Repository ready${NC}"

# ── Create .env if not exists ─────────────────────────────
if [ ! -f .env ]; then
    echo ""
    echo -e "${BOLD}${BLUE}📝 Creating .env configuration...${NC}"
    cat > .env << EOF
# NEXUS v6.0 Configuration
# Generated by install.sh — customize as needed

# ── Ollama ──
OLLAMA_HOST=${OLLAMA_HOST}
OLLAMA_API_KEY=

# ── Model Routing ──
NEXUS_MODEL_FAST=${MODEL_FAST}
NEXUS_MODEL_STANDARD=${MODEL_STANDARD}
NEXUS_MODEL_THINK=${MODEL_THINK}

# ── Telegram Bot (optional) ──
NEXUS_TG_TOKEN=${TELEGRAM_TOKEN}
NEXUS_BUILD_TELEGRAM=${BUILD_TELEGRAM}
EOF
    echo -e "${GREEN}✓ .env created${NC}"
    echo -e "${YELLOW}  Edit ${INSTALL_DIR}/.env to add your API keys and Telegram token${NC}"
else
    echo -e "${GREEN}✓ .env already exists${NC}"
fi

# ── Create data directories ──────────────────────────────
mkdir -p memory/{sessions,skills,longterm}
mkdir -p data/{state,checkpoints,rag,error_learning,rate_limits,credentials,skills}

# ── Build Docker image ──────────────────────────────────
echo ""
echo -e "${BOLD}${BLUE}🐳 Building Docker image...${NC}"
echo -e "  ${YELLOW}This may take a few minutes on first run.${NC}"

$COMPOSE_CMD build --build-arg BUILD_WITH_TELEGRAM="$BUILD_TELEGRAM" 2>&1 | tail -5

if [ $? -eq 0 ]; then
    echo -e "${GREEN}✓ Docker image built${NC}"
else
    echo -e "${RED}✗ Docker build failed. Check the output above.${NC}"
    exit 1
fi

# ── Start ─────────────────────────────────────────────────
echo ""
echo -e "${CYAN}═══════════════════════════════════════════════════════${NC}"
echo -e "${BOLD}${GREEN}  NEXUS v6.0 installed successfully! 🚀${NC}"
echo -e "${CYAN}═══════════════════════════════════════════════════════${NC}"
echo ""
echo -e "  ${BOLD}Quick start:${NC}"
echo ""
echo -e "  ${CYAN}# Start NEXUS (CLI mode)${NC}"
echo -e "  cd ${INSTALL_DIR} && ${COMPOSE_CMD} up nexus"
echo ""
echo -e "  ${CYAN}# Start NEXUS with Telegram bot${NC}"
echo -e "  cd ${INSTALL_DIR} && ${COMPOSE_CMD} --profile telegram up nexus-telegram"
echo ""
echo -e "  ${CYAN}# Start in background${NC}"
echo -e "  cd ${INSTALL_DIR} && ${COMPOSE_CMD} up -d nexus"
echo ""
echo -e "  ${CYAN}# View logs${NC}"
echo -e "  cd ${INSTALL_DIR} && ${COMPOSE_CMD} logs -f nexus"
echo ""
echo -e "  ${CYAN}# Stop${NC}"
echo -e "  cd ${INSTALL_DIR} && ${COMPOSE_CMD} down"
echo ""
echo -e "  ${BOLD}Configure:${NC} Edit ${INSTALL_DIR}/.env"
echo -e "  ${BOLD}Docs:${NC}     https://github.com/***REMOVED***/nexus-toti"
echo ""

# ── Auto-start if NEXUS_AUTO_START=1 ─────────────────────
if [ "${NEXUS_AUTO_START}" = "1" ]; then
    echo -e "${BOLD}${BLUE}🚀 Auto-starting NEXUS...${NC}"
    if [ -n "$TELEGRAM_TOKEN" ]; then
        $COMPOSE_CMD --profile telegram up -d nexus-telegram
    else
        $COMPOSE_CMD up -d nexus
    fi
    echo -e "${GREEN}✓ NEXUS is running!${NC}"
fi